type: dev-environment
# This configuration launches a blank dev environment

# Uncomment "python" or "image" (to configure the environment)

python: 3.11

# image: ghcr.io/huggingface/text-generation-inference:latest

ide: vscode

# (Optional) Configure `gpu`, `memory`, `disk`, etc
resources:
  gpu: 16GB..
