workflows:
  - name: hello-conda
    provider: bash
    commands:
      - conda install pandas -y
      - python usage/python/hello_pandas.py

  - name: setup-conda
    help: "This workflow prepares the myenv Conda environment"
    provider: bash
    commands:
      - conda env create --file usage/conda/environment.yaml
    artifacts:
      - path: /opt/conda/envs/myenv

  - name: use-conda
    help: "This workflow reuses the Conda environment prepared in the `setup-conda` workflow"
    provider: bash
    deps:
      - workflow: setup-conda
    commands:
      - conda activate myenv
      - python usage/conda/hello_pandas.py

  - name: xgboost-env
    help: "This workflow prepares myenv Conde environment with xgboost installed."
    commands:
      - conda env create --file usage/conda/xgboost.yaml
      - conda activate xgboost-env
      - conda install -y scikit-learn
      - conda install -y xgboost
    provider: bash
    artifacts:
      - path: /opt/conda/envs/xgboost-env
